### PR TITLE
Adds python validation workflows

### PR DESCRIPTION
**Pull request by mouse-reeve**
I'm thinking that it would be helpful to get this in place early, but I'm happy to chill if it's more of a hassle right now than it's worth. And I don't want to have Black create a bunch of conflicts with existing work

Things to fix before this is ready because I need to go to work right now:
 - [x] Make it clear how to actually run black
 - [x] Make the pylint one actually work
 - [x] Add tests workflow
 - [x] Update code formatting

### CODE REVIEW

**Comment by hughrun** [comment]
Sounds good. FYI the original repo came with `tox` and once I worked out what that is, it seems to be useful. So I've reconfigured it to add options for `black`, `pylint`, and `pytest`.

I'm currently finalising linting of the tests, then tentatively this may be almost ready - so yes please don't pull this before checking with me, but I'm linting and testing everything so it should be relatively plain sailing once this first bunch of stuff is complete.

**Comment by mouse-reeve** [comment]
Thank you, I *just* realized tox is there and I haven't figured out how to get it to work with pylint but it made getting the workflow for the tests so much easier

**Comment by mouse-reeve** [comment]
Okay it looks like the workflows work! I'll just leave this until you're ready for it.

**Comment by hughrun** [comment]
Sorry just pushed up a bunch of stuff that probably has broken your model!

I moved the main code into a `src` directory to make it easier to package with `build`.

So tox commands should be:

* `tox` - will run pytest
* `tox` - will run black on everything
* `tox -e pylint -- src` will run pylint on the actual code
* `tox -e pylint -- tests` will run pylint on the tests

I'll add a CONTRIBUTING page soon to clarify.

**Comment by mouse-reeve** [comment]
No worries! I'll check back in tomorrow morning and update this to reflect where it's at.

**Comment by mouse-reeve** [comment]
Pylint isn't working for me locally so I'm trying to get it to pass here. I can revert the changes to the tests if it's easier to not have them in this branch

**Comment by mouse-reeve** [comment]
@hughrun ready to merge?

**Pull request merged**
